esp_toml_version = 1.0
firmware_images_url = "https://codfish-pt.github.io/bin/"

supported_apps = ["flui", "test"]

[flui]
chipsets = ["ESP32C3"]
image.esp32c3 = "esp32c3_flui.bin"

[test]
chipsets = ["ESP32C3"]
image.esp32c3 = "firmware.bin"
